In [1]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (3.7)
Requirement already satisfied: joblib in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: tqdm in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: click in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.1.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2022.9.13)
Requirement already satisfied: colorama in c:\users\chigerwe\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.5)

WARNING: You are using pip version 22.0.4; however, version 22.3 is available.
You should consider upgrading via the 'C:\Users\Chigerwe\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [2]:
import numpy as np # linear algebra
import pandas as pd

In [3]:
truenews = pd.read_csv('True.csv')
fakenews = pd.read_csv('Fake.csv')

In [4]:
fakenews.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
truenews.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
fakenews.describe()

,title,text,subject,date
count,23481,23481,23481,23481
unique,17903,17455,6,1681
top,MEDIA IGNORES Time That Bill Clinton FIRED His...,,News,"May 10, 2017"
freq,6,626,9050,46

In [7]:
truenews.describe()

,title,text,subject,date
count,21417,21417,21417,21417
unique,20826,21192,2,716
top,Factbox: Trump fills top jobs for his administ...,(Reuters) - Highlights for U.S. President Dona...,politicsNews,"December 20, 2017"
freq,14,8,11272,182

In [8]:
truenews['True/Fake']='True'
fakenews['True/Fake']='Fake'

In [9]:
# Combine the 2 DataFrames into a single data frame
news = pd.concat([truenews, fakenews])
news["Article"] = news["title"] + news["text"]
news.sample(frac = 1) #Shuffle 100%

,title,text,subject,date,True/Fake,Article
18255,FORMER DEMOCRAT WHO VOTED FOR TRUMP RIPS DEMOC...,After a Fox Business interview earlier in the ...,left-news,"Jul 26, 2017",Fake,FORMER DEMOCRAT WHO VOTED FOR TRUMP RIPS DEMOC...
1321,Trump’s Son Gets Schooled After Claiming Cons...,"A comedian went too far today and for that, sh...",News,"May 30, 2017",Fake,Trump’s Son Gets Schooled After Claiming Cons...
1674,Scott Baio Gets His A** Handed To Him By Erin...,Erin Moran s family just declared war on Scott...,News,"April 26, 2017",Fake,Scott Baio Gets His A** Handed To Him By Erin...
13086,‘NAFTA BOY’ BILL CLINTON HECKLED At Detroit La...,,politics,"Sep 5, 2016",Fake,‘NAFTA BOY’ BILL CLINTON HECKLED At Detroit La...
10060,"Republican Cruz crushes Trump in Wisconsin, sa...",MILWAUKEE (Reuters) - Republican Ted Cruz easi...,politicsNews,"April 5, 2016",True,"Republican Cruz crushes Trump in Wisconsin, sa..."
...,...,...,...,...,...,...
9149,"Democrats link guns to terrorism, turn to gun ...",WASHINGTON (Reuters) - President Barack Obama ...,politicsNews,"June 13, 2016",True,"Democrats link guns to terrorism, turn to gun ..."
8434,‘Christians’ Who Leave Fake $20 Tips For Serv...,Christian fundamentalists picked on the wrong ...,News,"January 30, 2016",Fake,‘Christians’ Who Leave Fake $20 Tips For Serv...
4747,President Obama Warns Putin: Don’t Hack Our E...,"Recently, intelligence agencies, including the...",News,"September 6, 2016",Fake,President Obama Warns Putin: Don’t Hack Our E...
12415,WOW! SCRUBBED 1998 GEORGE SOROS Video Resurfac...,Knowing there were problems ahead for the Jews...,politics,"Nov 12, 2016",Fake,WOW! SCRUBBED 1998 GEORGE SOROS Video Resurfac...
4122,Trump's 'big announcement' on tax to be broad ...,WASHINGTON (Reuters) - President Donald Trump’...,politicsNews,"April 22, 2017",True,Trump's 'big announcement' on tax to be broad ...

#Data Cleaning

In [10]:

from nltk.corpus import stopwords
import string
import nltk
#nltk.download()

In [11]:
def process_text(s):

    # Check string to see if they are a punctuation
    nopunc = [char for char in s if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Convert string to lowercase and remove stopwords
    clean_string = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean_string

In [12]:
# Tokenize the Article
#rerun, takes LOOOONG
news['Clean Text'] = news['Article'].apply(process_text)

KeyboardInterrupt:

In [13]:
news.sample(5)

,title,text,subject,date,True/Fake,Article
17805,Cambodia's Hun Sen renews criticism of United ...,PHNOM PENH (Reuters) - Cambodian Prime Ministe...,worldnews,"October 11, 2017",True,Cambodia's Hun Sen renews criticism of United ...
17676,"No visas, bad jobs: Venezuelan emigrants reluc...","CARACAS/SAN CRISTOBAL, Venezuela (Reuters) - E...",worldnews,"October 12, 2017",True,"No visas, bad jobs: Venezuelan emigrants reluc..."
6911,Trump clear on China's stance on call with Tai...,BEIJING (Reuters) - China said on Monday U.S. ...,politicsNews,"December 5, 2016",True,Trump clear on China's stance on call with Tai...
13267,Chinese police detain 11 over deadly Tianjin s...,BEIJING (Reuters) - Chinese police have detain...,worldnews,"December 3, 2017",True,Chinese police detain 11 over deadly Tianjin s...
17602,LOL! PRESIDENT TRUMP Wants Network Who Pushes ...,"Earlier today, President Trump tweeted: We sh...",left-news,"Nov 27, 2017",Fake,LOL! PRESIDENT TRUMP Wants Network Who Pushes ...

In [15]:
#!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.1.3-cp310-cp310-win_amd64.whl (7.5 MB)
     ---------------------------------------- 7.5/7.5 MB 2.3 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.17.3 in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.23.4)
Collecting scipy>=1.3.2
  Downloading scipy-1.9.3-cp310-cp310-win_amd64.whl (40.1 MB)
     ---------------------------------------- 40.1/40.1 MB 2.0 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.0.0 in c:\users\chigerwe\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.2.0)
Installing collected packages: threadpoolctl, scipy, scikit-learn
Successfully installed scikit-learn-1.1.3 scipy-1.9.3 threadpoolctl-3.1.0

WARNING: You are using pip version 22.0.4; however, version 22.3 is available.
You should consider upgrading via the 'C:\Users\Chigerwe\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
bow_transformer = CountVectorizer(analyzer=process_text).fit(news['Clean Text'])

print(len(bow_transformer.vocabulary_)) #Total vocab words

KeyError: 'Clean Text'

In [18]:
#Bag-of-Words (bow) transform the entire DataFrame of text
news_bow = bow_transformer.transform(news['Clean Text'])

NameError: name 'bow_transformer' is not defined